[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

# Save configs ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''self:leave()'''
payload = '''utilitools.config.save(mods["quick-playtest"])'''
position = "before"
target = "states/Editor.lua"
times = 2
