[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

# Font cache ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if not cs.customFonts[fontName] then'''
payload = '''
local QP_filePath = cLevel .. event.fontpath
local QP_modtime = quickPlaytest.getModtime("font", QP_filePath)
if not cs.customFonts[fontName] or not quickPlaytest.fileLoaded("font", QP_filePath, QP_modtime) then
'''
position = "at"
target = "levelformat/events/Vfx/Deco/loadCustomFont.lua"
times = 1

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if not pcall(function() cs.customFonts[fontName] = love.graphics.newImageFont(filename, chrmap, chrspacing) end) then'''
payload = '''
if not pcall(function()
	cs.customFonts[fontName] = love.graphics.newImageFont(filename, chrmap, chrspacing)
	quickPlaytest.loadFile("font", QP_filePath, QP_modtime)
end) then
'''
position = "at"
target = "levelformat/events/Vfx/Deco/loadCustomFont.lua"
times = 1

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if not pcall(function() cs.customFonts[fontName] = love.graphics.newFont(filename, event.ttfFontSize,'mono') cs.customFonts[fontName]:setFilter("nearest", "nearest", 1) end) then'''
payload = '''
if not pcall(function()
	cs.customFonts[fontName] = love.graphics.newFont(filename, event.ttfFontSize,'mono')
	cs.customFonts[fontName]:setFilter("nearest", "nearest", 1)
	quickPlaytest.loadFile("font", QP_filePath, QP_modtime)
end) then
'''
position = "at"
target = "levelformat/events/Vfx/Deco/loadCustomFont.lua"
times = 1
