[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

# Sound cache ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
if not cs.soundEffects[event.sound] then
	if not sounds[event.sound] then
'''
payload = '''
if not sounds[event.sound] then
	local QP_filePath = cLevel .. event.sound
	local QP_modtime = quickPlaytest.getModtime("sound", QP_filePath)
	if not cs.soundEffects[event.sound] or not quickPlaytest.fileLoaded("sound", QP_filePath, QP_modtime) then
'''
position = "at"
target = "levelformat/events/Vfx/playSound.lua"
times = 1

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if not pcall(function() cs.soundEffects[event.sound] = love.sound.newSoundData(filename) end) then'''
payload = '''
if not pcall(function()
	cs.soundEffects[event.sound] = love.sound.newSoundData(filename)
	quickPlaytest.loadFile("sound", QP_filePath, QP_modtime)
end) then
'''
position = "at"
target = "levelformat/events/Vfx/playSound.lua"
times = 1
